server:
  port : 8180

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/testdb
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
